String home = 'Home';
String BUTTON_CHANGE_LANG = 'BUTTON_CHANGE_LANG';
String BUTTON_CHANGE_THEME = 'BUTTON_CHANGE_THEME';
String BUTTON_LOGIN = 'BUTTON_LOGIN';
String BUTTON_SING_OUT = 'BUTTON_SING_OUT';